# Generated by Django 5.2.6 on 2025-09-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
